name: sms_sender
description: A local package for sending SMS in both foreground and background.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.crisander.sms_sender
        pluginClass: SmsSenderPlugin
